# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 
    en: ☆☆ argot cozy blog ☆☆  
    es: ☆☆ argot cozy blog ☆☆ 
email:
description: 
    en: Yet another blog about *nix stuff
    es: Otro blog sobre *nix
index:
    en:
    es: index_es.html
feed:
    en: /feed.xml
    es: /feed_es.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.argot.moe" # the base hostname & protocol for your site
twitter_username:
github_username: argot42

# Build settings
markdown: kramdown
